/**
 * 60 charlas de seguridad laboral / prevención de riesgos (charlas de 5 minutos).
 * Rotan automáticamente sin repetirse durante 60 días corridos (aprox. 2 meses)
 * antes de volver a empezar el ciclo. Ver charlaService.js para la lógica de selección.
 */
module.exports = [
  {
    titulo: 'Uso correcto de los Elementos de Protección Personal (EPP)',
    objetivo: 'Recordar que el EPP es la última barrera de protección, no la primera solución.',
    puntos: ['Antes de usar cualquier EPP, revisa que esté en buen estado: sin roturas, cortes ni piezas faltantes.', 'Usa siempre el EPP indicado para la tarea específica que vas a realizar, no el que tengas más a mano.', "El EPP dañado o vencido debe reportarse y reemplazarse de inmediato, nunca reutilizarse 'por mientras'.", 'Ponte el EPP ANTES de iniciar la tarea, no cuando ya estás expuesto al riesgo.'],
    reflexion: 'El EPP no elimina el riesgo, solo reduce sus consecuencias: la prevención empieza antes, evitando el riesgo en su origen.',
  },
  {
    titulo: 'Trabajo seguro en altura',
    objetivo: 'Toda caída de altura puede ser grave o fatal; la prevención es siempre más barata que la reparación.',
    puntos: ['Todo trabajo sobre 1.8 metros requiere sistema de protección contra caídas (arnés, línea de vida, puntos de anclaje certificados).', 'Verifica que el punto de anclaje soporte el peso indicado y esté correctamente certificado.', 'Nunca trabajes en altura solo: siempre debe haber un compañero o supervisor que pueda asistir en caso de emergencia.', 'Antes de subir, revisa el estado del arnés, mosquetones y cuerdas: cualquier desgaste es motivo de detención.'],
    reflexion: 'Si tienes dudas sobre la seguridad de un trabajo en altura, detente y consulta. Ninguna tarea justifica un riesgo de caída.',
  },
  {
    titulo: 'Manejo manual de cargas',
    objetivo: 'La mayoría de las lesiones lumbares se originan por una mala técnica de levantamiento, no por el peso en sí.',
    puntos: ['Evalúa el peso antes de levantar: si supera los 25 kg, pide ayuda o usa un medio mecánico.', 'Flexiona las rodillas, mantén la espalda recta y acerca la carga al cuerpo antes de levantar.', 'Evita giros bruscos de tronco mientras cargas; mueve los pies en vez de torcer la espalda.', 'Organiza el trayecto antes de levantar: despeja el camino y asegura buen agarre y visibilidad.'],
    reflexion: 'Cuidar tu espalda hoy evita que mañana no puedas trabajar ni disfrutar tiempo con tu familia.',
  },
  {
    titulo: 'Prevención de golpes y cortes con herramientas manuales',
    objetivo: 'Las heridas por herramientas manuales son de las más frecuentes y más fáciles de evitar.',
    puntos: ['Usa cada herramienta solo para la función que fue diseñada; nunca la improvises para otra tarea.', 'Revisa el estado de mangos, filos y empuñaduras antes de cada uso.', 'Mantén las manos y el cuerpo fuera de la línea de corte o golpe al trabajar.', 'Guarda las herramientas cortopunzantes en su funda o estuche cuando no las estés usando.'],
    reflexion: 'Una herramienta en mal estado es tan peligrosa como no usar protección: revisa siempre antes de trabajar.',
  },
  {
    titulo: 'Seguridad en el uso de herramientas eléctricas',
    objetivo: 'El contacto eléctrico y las partes móviles son los principales riesgos de estas herramientas.',
    puntos: ['Inspecciona cables, enchufes y carcasa antes de conectar cualquier herramienta eléctrica.', 'Nunca uses herramientas eléctricas con las manos mojadas o en ambientes húmedos sin protección adecuada.', "Usa siempre las guardas de seguridad; nunca las retires para 'trabajar más rápido'.", 'Desconecta la herramienta antes de cambiar accesorios, discos o brocas.'],
    reflexion: 'Una descarga eléctrica puede ocurrir en segundos: la prevención toma solo unos minutos de revisión.',
  },
  {
    titulo: 'Bloqueo y etiquetado (LOTO)',
    objetivo: 'El bloqueo y etiquetado evita que un equipo se energice mientras alguien lo está interviniendo.',
    puntos: ['Identifica todas las fuentes de energía del equipo (eléctrica, hidráulica, neumática, mecánica) antes de intervenir.', 'Bloquea y etiqueta cada fuente de energía con tu candado personal, nunca compartido.', 'Verifica la ausencia de energía antes de comenzar el trabajo (prueba de arranque en vacío).', 'Solo la persona que colocó el candado puede retirarlo, al finalizar el trabajo.'],
    reflexion: 'Nunca asumas que un equipo está apagado: verifica siempre antes de intervenir.',
  },
  {
    titulo: 'Espacios confinados',
    objetivo: 'Los espacios confinados pueden tener atmósferas peligrosas invisibles: gases, falta de oxígeno o riesgo de asfixia.',
    puntos: ['Nunca ingreses a un espacio confinado sin el permiso de trabajo correspondiente.', 'Verifica la atmósfera con detector de gases antes de ingresar y de forma continua mientras trabajas.', 'Debe existir siempre un vigía en el exterior en comunicación permanente con quien está adentro.', 'Ten claro el plan de rescate antes de ingresar, no después de un incidente.'],
    reflexion: 'Lo que no se ve puede ser lo más peligroso: nunca confíes en la apariencia de un espacio confinado.',
  },
  {
    titulo: 'Prevención de incendios en el lugar de trabajo',
    objetivo: 'El triángulo del fuego (combustible, oxígeno y calor) está presente en casi todos los lugares de trabajo.',
    puntos: ['Mantén los materiales combustibles alejados de fuentes de calor o chispas.', 'Conoce la ubicación de los extintores y las vías de evacuación de tu área de trabajo.', 'No sobrecargues enchufes ni uses cables eléctricos en mal estado.', 'Reporta de inmediato cualquier olor a quemado, humo o chispas inusuales.'],
    reflexion: 'Un incendio se combate mejor antes de que empiece: la prevención diaria es la mejor herramienta.',
  },
  {
    titulo: 'Uso correcto de extintores',
    objetivo: 'Saber usar un extintor a tiempo puede evitar que un pequeño fuego se convierta en una tragedia.',
    puntos: ['Identifica el tipo de extintor correcto según la clase de fuego (A, B, C, etc.).', 'Recuerda la técnica PASE: Placa (quita el seguro), Apunta a la base del fuego, Sujeta y aprieta la palanca, Extiende con movimiento de barrido.', 'Nunca le des la espalda al fuego mientras te retiras después de usar el extintor.', 'Si el fuego crece o no puedes controlarlo en segundos, evacúa y da la alarma.'],
    reflexion: 'Actuar rápido y correctamente en los primeros segundos marca la diferencia.',
  },
  {
    titulo: 'Primeros auxilios básicos',
    objetivo: 'Saber actuar en los primeros minutos de una emergencia puede salvar una vida.',
    puntos: ['Evalúa la escena antes de actuar: asegúrate de que sea seguro acercarte a la víctima.', 'Pide ayuda de inmediato y activa el protocolo de emergencia de tu lugar de trabajo.', 'No muevas a una persona con sospecha de lesión en columna, salvo riesgo inminente.', 'Mantén la calma: tu tranquilidad ayuda a que la víctima también se mantenga más estable.'],
    reflexion: 'No necesitas ser experto para ayudar: actuar rápido y pedir ayuda ya es una gran diferencia.',
  },
  {
    titulo: 'Señalización de seguridad',
    objetivo: 'Las señales de seguridad comunican riesgos y acciones de forma rápida y universal.',
    puntos: ['Aprende a identificar los colores y formas: rojo (prohibición/peligro), amarillo (advertencia), verde (información/emergencia), azul (obligación).', 'Respeta siempre la señalización, incluso si el área parece despejada momentáneamente.', 'Reporta señalética dañada, tapada o mal ubicada.', 'Nunca retires ni tapes una señal de seguridad sin autorización.'],
    reflexion: 'La señalización solo funciona si la respetamos: es un lenguaje común que cuida a todos.',
  },
  {
    titulo: 'Orden y limpieza (5S)',
    objetivo: 'Un lugar de trabajo desordenado multiplica el riesgo de accidentes, tropiezos y caídas.',
    puntos: ['Clasifica: mantén en tu área solo lo necesario para la tarea del día.', 'Ordena: cada herramienta y material debe tener un lugar definido.', 'Limpia: deja tu puesto de trabajo limpio al finalizar la jornada.', 'Estandariza y mantén el hábito: el orden se construye día a día, no una sola vez.'],
    reflexion: 'El orden no es estético, es preventivo: menos desorden significa menos accidentes.',
  },
  {
    titulo: 'Prevención de caídas al mismo nivel',
    objetivo: 'Las caídas al mismo nivel son de los accidentes más comunes y más subestimados.',
    puntos: ['Mantén los pasillos y vías de tránsito libres de cables, herramientas y materiales.', 'Limpia de inmediato cualquier derrame de líquidos en el piso.', 'Usa calzado de seguridad antideslizante adecuado para tu tipo de trabajo.', 'Camina, no corras, dentro de las instalaciones de trabajo.'],
    reflexion: 'Un piso despejado y calzado adecuado previenen la mayoría de estas caídas.',
  },
  {
    titulo: 'Manejo seguro de sustancias químicas',
    objetivo: 'Muchas sustancias de uso cotidiano en el trabajo pueden ser peligrosas si no se manejan correctamente.',
    puntos: ['Lee siempre la etiqueta y la hoja de seguridad (FDS) antes de usar un producto químico.', 'Usa el EPP específico indicado para cada sustancia (guantes, lentes, respirador si corresponde).', 'Nunca mezcles productos químicos sin conocer las reacciones posibles.', 'Almacena los productos según su compatibilidad, en lugares ventilados y etiquetados.'],
    reflexion: 'Conocer lo que manipulas es la primera forma de protegerte.',
  },
  {
    titulo: 'Hojas de seguridad (MSDS/FDS)',
    objetivo: 'La hoja de datos de seguridad es la fuente oficial de información sobre cada producto químico.',
    puntos: ['Debe estar disponible y accesible para todos los que trabajan con ese producto.', 'Indica riesgos, EPP requerido, primeros auxilios y manejo ante derrames.', 'Revísala antes del primer uso de cualquier producto nuevo.', 'Ante cualquier accidente con químicos, la hoja de seguridad guía la respuesta médica.'],
    reflexion: 'Tomarte dos minutos para leerla puede evitar una exposición grave.',
  },
  {
    titulo: 'Ergonomía en el puesto de trabajo',
    objetivo: 'Las malas posturas mantenidas en el tiempo generan lesiones que aparecen silenciosamente.',
    puntos: ['Ajusta tu puesto de trabajo (altura de silla, pantalla, herramientas) a tu propio cuerpo.', 'Evita mantener posturas forzadas o repetitivas por periodos prolongados sin pausas.', 'Alterna tareas cuando sea posible para variar los grupos musculares usados.', 'Realiza pausas activas y estiramientos durante la jornada.'],
    reflexion: 'Cuidar tu postura hoy es invertir en tu movilidad de mañana.',
  },
  {
    titulo: 'Prevención de lesiones lumbares',
    objetivo: 'La espalda baja es una de las zonas más afectadas por el trabajo físico mal ejecutado.',
    puntos: ['Fortalece tu core con ejercicio regular fuera del trabajo, si tu condición de salud lo permite.', 'Evita cargar peso con la espalda curva; usa siempre las piernas para levantar.', 'Usa ayudas mecánicas (carros, grúas, gatos) cuando estén disponibles.', "Escucha a tu cuerpo: el dolor es una señal de alerta, no algo que 'aguantar no más'."],
    reflexion: 'Una lesión lumbar puede tardar meses en sanar: la prevención toma solo segundos.',
  },
  {
    titulo: 'Fatiga laboral y microsueños',
    objetivo: 'La fatiga reduce la atención y los reflejos, aumentando el riesgo de accidentes, especialmente al conducir u operar maquinaria.',
    puntos: ['Duerme lo suficiente antes de tu turno; el descanso es parte de tu responsabilidad laboral.', 'Reconoce las señales de fatiga: bostezos frecuentes, pesadez de párpados, pérdida de concentración.', 'Si sientes fatiga extrema, informa a tu supervisor antes de operar equipos o vehículos.', "Toma tus pausas y descansos programados, no los sacrifiques por 'avanzar más rápido'."],
    reflexion: 'Un trabajador descansado es un trabajador seguro, para sí mismo y para su equipo.',
  },
  {
    titulo: 'Hidratación en trabajos al aire libre',
    objetivo: 'La deshidratación reduce el rendimiento físico y mental mucho antes de que sientas sed.',
    puntos: ['Bebe agua de forma regular durante toda la jornada, no solo cuando sientas sed.', 'Evita bebidas con alto contenido de azúcar o cafeína como reemplazo del agua.', 'En días calurosos, aumenta la frecuencia de hidratación y busca sombra en las pausas.', 'Reconoce síntomas de deshidratación: dolor de cabeza, mareo, calambres, fatiga inusual.'],
    reflexion: 'Hidratarte no es opcional en trabajo físico al aire libre: es una medida de seguridad.',
  },
  {
    titulo: 'Exposición a radiación UV',
    objetivo: 'La radiación solar UV puede causar quemaduras, daño ocular y a largo plazo aumentar el riesgo de cáncer de piel.',
    puntos: ['Usa protector solar, lentes con filtro UV, sombrero de ala ancha y ropa que cubra la piel expuesta.', 'Evita exposición directa prolongada entre las 11:00 y las 16:00, horario de mayor radiación.', 'Busca sombra en cada pausa disponible, incluso en días nublados.', 'Revisa el Índice UV del día (como el reporte diario) para planificar tus tareas al aire libre.'],
    reflexion: 'El daño solar es acumulativo: protegerte hoy cuida tu salud a largo plazo.',
  },
  {
    titulo: 'Golpes de calor y estrés térmico',
    objetivo: 'El calor extremo puede provocar desde calambres hasta un golpe de calor, que es una emergencia médica.',
    puntos: ['Reconoce los síntomas tempranos: sudoración excesiva, debilidad, mareo, calambres musculares.', 'Si los síntomas avanzan a confusión, piel caliente y seca, o pérdida de conciencia, es una emergencia: actúa de inmediato.', 'Aumenta la frecuencia de pausas e hidratación en días de altas temperaturas.', 'Usa ropa liviana, transpirable y de colores claros cuando la tarea lo permita.'],
    reflexion: 'El golpe de calor puede ser mortal: ante la duda, detén la actividad y busca ayuda.',
  },
  {
    titulo: 'Trabajo en condiciones de frío extremo',
    objetivo: 'El frío intenso también representa riesgos serios: hipotermia, congelación y pérdida de destreza motora.',
    puntos: ['Usa ropa en capas que permita ajustar el abrigo según la actividad.', 'Protege especialmente manos, pies, orejas y nariz, zonas más propensas a congelación.', 'Realiza pausas en lugares templados cuando sea posible.', 'Reconoce signos de hipotermia: escalofríos intensos, confusión, torpeza en los movimientos.'],
    reflexion: 'El frío reduce tu capacidad de reacción sin que lo notes: abrígate antes de sentir frío, no después.',
  },
  {
    titulo: 'Ruido laboral y protección auditiva',
    objetivo: 'La exposición prolongada a ruido intenso causa daño auditivo irreversible y silencioso.',
    puntos: ['Usa protección auditiva (tapones o orejeras) en zonas con niveles de ruido elevados.', 'El daño auditivo no duele ni se nota de inmediato, pero es acumulativo y permanente.', 'Si necesitas alzar la voz para hablar con alguien a un metro de distancia, el ruido probablemente ya requiere protección.', 'Realiza tus controles auditivos periódicos si tu trabajo te expone a ruido constante.'],
    reflexion: 'Cuida tu audición hoy: una vez perdida, no se recupera.',
  },
  {
    titulo: 'Vibraciones mano-brazo',
    objetivo: 'El uso prolongado de herramientas vibratorias puede dañar nervios, vasos sanguíneos y articulaciones de manos y brazos.',
    puntos: ['Usa herramientas con sistemas antivibración cuando estén disponibles.', 'Alterna tareas para reducir el tiempo continuo de exposición a la vibración.', 'Usa guantes adecuados que ayuden a amortiguar la vibración.', 'Reporta hormigueo, adormecimiento o cambios de color en los dedos.'],
    reflexion: 'Los síntomas de daño por vibración aparecen de a poco: prestar atención a tiempo evita lesiones mayores.',
  },
  {
    titulo: 'Manejo defensivo de vehículos',
    objetivo: 'La mayoría de los accidentes viales se pueden prevenir anticipando el error de otros.',
    puntos: ['Respeta siempre los límites de velocidad y las distancias de seguridad.', 'Anticipa las acciones de otros conductores, peatones y equipos en movimiento.', 'Nunca uses el celular mientras conduces.', 'Revisa el estado del vehículo antes de cada turno: frenos, luces, espejos, neumáticos.'],
    reflexion: 'Conducir a la defensiva no es desconfiar de todos, es estar siempre preparado.',
  },
  {
    titulo: 'Seguridad vial dentro de la obra o faena',
    objetivo: 'El tránsito interno de vehículos y peatones es una de las principales causas de accidentes graves en faenas.',
    puntos: ['Respeta la señalización interna y las velocidades máximas establecidas.', 'Usa siempre chaleco reflectante en zonas de tránsito de vehículos.', 'Mantén contacto visual con el operador antes de cruzar frente a un vehículo o máquina.', 'Nunca camines por zonas de maniobra de vehículos pesados sin autorización.'],
    reflexion: 'Dentro de la faena, peatones y vehículos deben convivir con reglas claras y respetadas por todos.',
  },
  {
    titulo: 'Operación segura de maquinaria pesada',
    objetivo: 'Solo personal capacitado y autorizado debe operar maquinaria pesada.',
    puntos: ['Realiza siempre la inspección pre-uso antes de encender el equipo.', 'Verifica que el área esté despejada de personas antes de iniciar maniobras.', 'Usa la bocina y señales de advertencia antes de cada movimiento, especialmente en retroceso.', 'Nunca operes un equipo para el que no estás certificado, aunque parezca sencillo.'],
    reflexion: 'La maquinaria pesada exige respeto constante: un segundo de distracción puede ser irreversible.',
  },
  {
    titulo: 'Distancia de seguridad con equipos en movimiento',
    objetivo: 'El radio de giro y los puntos ciegos de la maquinaria pesada son más grandes de lo que parece.',
    puntos: ['Mantente siempre a la vista del operador; si no puedes verlo, él tampoco puede verte a ti.', 'Respeta las zonas de exclusión delimitadas alrededor de equipos en operación.', 'Nunca te acerques a un equipo en movimiento para dar indicaciones; espera a que se detenga.', 'Usa siempre elementos reflectantes que te hagan visible para los operadores.'],
    reflexion: 'La distancia de seguridad no es desconfianza, es respeto por el riesgo real que implica la maquinaria.',
  },
  {
    titulo: 'Izaje de cargas y uso de grúas',
    objetivo: 'Una carga mal izada puede caer, golpear o aplastar a quien esté cerca.',
    puntos: ['Verifica que la carga esté correctamente eslingada y equilibrada antes de izar.', 'Nunca te ubiques ni permitas que nadie pase bajo una carga suspendida.', 'Respeta la capacidad máxima de carga del equipo utilizado.', 'El izaje debe ser dirigido por una sola persona (rigger/señalero) claramente identificada.'],
    reflexion: 'Una carga suspendida siempre debe tratarse como un riesgo activo, nunca como algo controlado por completo.',
  },
  {
    titulo: 'Andamios: armado y uso seguro',
    objetivo: 'Un andamio mal armado es tan peligroso como trabajar sin protección alguna.',
    puntos: ['El armado debe realizarlo personal capacitado, siguiendo las especificaciones del fabricante.', 'Verifica que el andamio esté sobre una base firme, nivelada y con los elementos de anclaje correspondientes.', 'Nunca uses un andamio sin barandas, rodapiés y plataformas completas.', 'No sobrecargues el andamio más allá de su capacidad indicada.'],
    reflexion: 'Revisa siempre antes de subir: un andamio incompleto es un andamio inseguro.',
  },
  {
    titulo: 'Excavaciones y zanjas',
    objetivo: 'El colapso de una zanja puede ocurrir en segundos y sin previo aviso.',
    puntos: ['Toda excavación mayor a 1.5 metros debe contar con entibación o talud adecuado.', 'Verifica la ubicación de instalaciones subterráneas (agua, gas, electricidad) antes de excavar.', 'Nunca ingreses a una zanja sin la autorización y las medidas de protección correspondientes.', 'Mantén el material excavado alejado del borde de la zanja.'],
    reflexion: 'El suelo puede parecer estable y no serlo: nunca subestimes el riesgo de una excavación.',
  },
  {
    titulo: 'Trabajo eléctrico: riesgo de electrocución',
    objetivo: 'La electricidad no se ve, no tiene olor y puede ser mortal en fracciones de segundo.',
    puntos: ['Solo personal eléctricamente autorizado debe intervenir instalaciones o equipos energizados.', 'Trata siempre un circuito como si estuviera energizado, hasta comprobar lo contrario.', 'Usa herramientas y EPP dieléctrico certificado para trabajos eléctricos.', 'Respeta las distancias mínimas de seguridad con líneas de alta tensión.'],
    reflexion: 'Ante la duda sobre si algo está energizado, la respuesta siempre debe ser: no lo toques.',
  },
  {
    titulo: 'Trabajo con gas y soldadura',
    objetivo: 'Los trabajos en caliente combinan riesgo de quemaduras, incendio y exposición a gases.',
    puntos: ['Verifica que no existan materiales combustibles cerca del área de soldadura.', 'Usa siempre EPP específico: careta, guantes de cuero, ropa ignífuga.', 'Asegura ventilación adecuada para evitar acumulación de gases.', 'Ten siempre un extintor disponible y a la vista durante el trabajo en caliente.'],
    reflexion: 'El trabajo en caliente requiere permiso previo: nunca improvises una soldadura sin autorización.',
  },
  {
    titulo: 'Manejo de residuos peligrosos',
    objetivo: 'Los residuos peligrosos mal gestionados pueden afectar tu salud y la del medio ambiente.',
    puntos: ['Segrega los residuos según su tipo y peligrosidad, nunca los mezcles.', 'Usa los contenedores y etiquetas correspondientes para cada tipo de residuo.', 'Almacena en zonas designadas, ventiladas y protegidas de la intemperie.', 'Reporta cualquier derrame de residuo peligroso de inmediato, sin intentar limpiarlo solo si no estás capacitado.'],
    reflexion: 'Un residuo mal manejado hoy puede convertirse en un problema de salud mañana.',
  },
  {
    titulo: 'Comunicación efectiva en el trabajo',
    objetivo: 'Muchos accidentes ocurren por instrucciones mal entendidas o información que no llegó a tiempo.',
    puntos: ['Confirma siempre que el mensaje fue entendido, no solo que fue dicho.', 'Usa comunicación clara y directa, especialmente en tareas de riesgo.', "No asumas que 'todos saben'; informa explícitamente sobre cambios o riesgos nuevos.", 'Fomenta que cualquier persona pueda detener una tarea si detecta un riesgo, sin temor a represalias.'],
    reflexion: 'La comunicación clara es una herramienta de prevención tan importante como cualquier EPP.',
  },
  {
    titulo: 'Reporte de incidentes y cuasi accidentes',
    objetivo: 'Un cuasi accidente es una advertencia gratuita: reportarlo evita que se repita con consecuencias reales.',
    puntos: ['Reporta todo incidente, por pequeño que parezca, sin temor a consecuencias.', 'Los cuasi accidentes (casi pasa algo) son información valiosa para prevenir accidentes futuros.', 'Entre más rápido se reporte, más rápido se puede corregir la causa raíz.', 'Reportar no es culpar a alguien, es proteger a todo el equipo.'],
    reflexion: 'Lo que no se reporta, no se puede corregir. Reportar es un acto de responsabilidad, no de debilidad.',
  },
  {
    titulo: 'Investigación de accidentes: aprender del error',
    objetivo: 'Cada accidente investigado a fondo es una oportunidad de evitar que vuelva a ocurrir.',
    puntos: ['El objetivo de investigar un accidente es encontrar causas, no culpables.', 'Busca siempre la causa raíz, no solo el hecho inmediato que provocó el accidente.', 'Involucra a los trabajadores directamente relacionados en el análisis del hecho.', 'Implementa y verifica que las medidas correctivas realmente se apliquen.'],
    reflexion: 'De cada accidente investigado con seriedad sale una lección que puede salvar a otro compañero.',
  },
  {
    titulo: 'Derecho a saber (obligación de informar)',
    objetivo: 'Todo trabajador tiene derecho a conocer los riesgos asociados a su puesto de trabajo antes de comenzar a realizarlo.',
    puntos: ['La empresa debe informarte los riesgos específicos de tu tarea antes de iniciarla.', 'Tienes derecho a preguntar y exigir claridad sobre cualquier riesgo que no entiendas.', 'Conocer el riesgo es el primer paso para poder prevenirlo.', 'Si sientes que no fuiste informado correctamente, puedes y debes solicitarlo.'],
    reflexion: 'Conocer el riesgo no da miedo, da herramientas para trabajar de forma más segura.',
  },
  {
    titulo: 'Uso correcto del arnés de seguridad',
    objetivo: 'Un arnés mal ajustado o mal anclado puede no cumplir su función en el momento en que más se necesita.',
    puntos: ['Ajusta correctamente todas las correas del arnés: piernas, pecho y hombros.', 'El punto de anclaje debe estar sobre tu cabeza siempre que sea posible, nunca a nivel de los pies.', 'Revisa el estado del arnés y los conectores antes de cada uso.', 'Nunca uses un arnés que haya sufrido una caída sin antes ser inspeccionado por un experto.'],
    reflexion: 'Un arnés bien colocado y bien anclado es la diferencia entre un susto y una tragedia.',
  },
  {
    titulo: 'Trabajo nocturno y visibilidad',
    objetivo: 'La baja visibilidad nocturna reduce el tiempo de reacción ante cualquier riesgo.',
    puntos: ['Usa iluminación adicional en las zonas de trabajo nocturno.', 'Utiliza ropa y elementos reflectantes en todo momento durante turnos nocturnos.', 'Extrema la precaución en el tránsito de vehículos y maquinaria durante la noche.', 'Reconoce que la fatiga se acentúa en turnos nocturnos: toma tus pausas con mayor rigor.'],
    reflexion: 'De noche, todo riesgo se magnifica: la iluminación y la visibilidad son tu primera defensa.',
  },
  {
    titulo: 'Prevención de incendios forestales',
    objetivo: 'En faenas cercanas a vegetación seca, una chispa puede convertirse rápidamente en un incendio de grandes proporciones.',
    puntos: ['Evita realizar trabajos en caliente en días de alerta por riesgo de incendio.', 'Mantén despejada de vegetación seca el área alrededor de fuentes de calor o chispas.', 'Conoce el protocolo de evacuación específico para riesgo de incendio forestal en tu faena.', 'Reporta de inmediato cualquier foco de humo o fuego, por pequeño que parezca.'],
    reflexion: 'En condiciones de sequía, la prevención de incendios es responsabilidad de todos, todo el tiempo.',
  },
  {
    titulo: 'Manejo del estrés y salud mental en el trabajo',
    objetivo: 'La salud mental es parte de la seguridad laboral: el estrés y la ansiedad también generan riesgo de accidentes.',
    puntos: ['Reconoce las señales de estrés excesivo: irritabilidad, dificultad para concentrarte, cansancio constante.', 'Conversa con tu supervisor o los canales de apoyo disponibles si sientes que no puedes con la carga.', 'Respeta tus pausas y tiempo de descanso, también son parte de tu salud.', 'Apoya a tus compañeros: muchas veces una conversación a tiempo evita una crisis mayor.'],
    reflexion: 'Cuidar la mente es tan importante como cuidar el cuerpo: pedir ayuda es un acto de fortaleza.',
  },
  {
    titulo: 'Consumo de alcohol y drogas: tolerancia cero',
    objetivo: 'El consumo de alcohol o drogas altera la percepción del riesgo y el tiempo de reacción.',
    puntos: ['Nunca te presentes a trabajar bajo los efectos de alcohol o drogas.', 'Informa si detectas a un compañero en condiciones no aptas para trabajar; puede salvarle la vida.', 'Recuerda que algunos medicamentos también pueden afectar tu capacidad de reacción: consulta si tienes dudas.', 'La política de tolerancia cero protege a todo el equipo, no solo a quien consume.'],
    reflexion: 'Trabajar en condiciones óptimas es una responsabilidad compartida entre tú y tu equipo.',
  },
  {
    titulo: 'Autocuidado y responsabilidad compartida',
    objetivo: 'La seguridad no depende solo de reglas, depende de que cada persona decida cuidarse y cuidar a otros.',
    puntos: ['Tu seguridad empieza con tus propias decisiones diarias, antes que con cualquier norma escrita.', 'Cuidar a un compañero también es tu responsabilidad, no solo la del supervisor.', "No aceptes 'siempre se ha hecho así' como justificación para una práctica insegura.", 'Pequeñas decisiones diarias construyen una cultura de seguridad sólida.'],
    reflexion: 'La seguridad es una decisión personal que se repite cada día, en cada tarea.',
  },
  {
    titulo: 'Liderazgo en seguridad: el rol del supervisor',
    objetivo: 'Un buen líder en seguridad no solo exige cumplimiento, da el ejemplo primero.',
    puntos: ['El supervisor debe ser el primero en cumplir las normas de seguridad, sin excepciones.', 'Reconocer y corregir con respeto, no con castigo, fortalece la cultura preventiva.', 'Escuchar las preocupaciones del equipo genera confianza y mejora la detección temprana de riesgos.', 'Celebrar el buen desempeño en seguridad refuerza los comportamientos correctos.'],
    reflexion: 'El ejemplo del líder pesa más que cualquier norma escrita en un papel.',
  },
  {
    titulo: 'Permisos de trabajo (PTS)',
    objetivo: 'Los permisos de trabajo seguro existen para asegurar que se evaluaron todos los riesgos antes de comenzar.',
    puntos: ['Nunca inicies una tarea de riesgo sin el permiso de trabajo correspondiente.', 'Revisa que las condiciones descritas en el permiso coincidan con la realidad del terreno.', 'El permiso debe ser válido para la tarea específica del día, no reutilizado de otra ocasión.', 'Si las condiciones cambian durante la tarea, detente y revisa el permiso nuevamente.'],
    reflexion: 'El permiso de trabajo no es un trámite, es una verificación real de que estás listo para trabajar seguro.',
  },
  {
    titulo: 'Trabajo en caliente',
    objetivo: 'Cualquier tarea que genere chispas, llama o calor intenso requiere control estricto del entorno.',
    puntos: ['Verifica y retira todo material combustible en un radio de seguridad antes de comenzar.', 'Cuenta siempre con un extintor y una persona vigilante durante el trabajo en caliente.', 'Realiza una inspección posterior al finalizar el trabajo, ya que el riesgo de incendio puede persistir.', 'Solicita siempre el permiso de trabajo en caliente antes de iniciar.'],
    reflexion: 'El fuego no avisa antes de empezar: la prevención debe estar lista antes de cada chispa.',
  },
  {
    titulo: 'Manejo seguro de escaleras portátiles',
    objetivo: 'Las escaleras portátiles son una de las principales causas de caídas de baja altura, pero con consecuencias serias.',
    puntos: ['Verifica que la escalera esté en buen estado y sea la adecuada para la tarea.', 'Apóyala en una superficie firme y nivelada, respetando el ángulo recomendado (4 a 1).', 'Mantén siempre tres puntos de apoyo al subir o bajar.', 'Nunca uses el último peldaño ni sobrepases el límite de altura indicado por el fabricante.'],
    reflexion: 'Una escalera bien usada es segura; una mal usada es una trampa silenciosa.',
  },
  {
    titulo: 'Prevención de atrapamientos',
    objetivo: 'Partes móviles de máquinas y equipos pueden atrapar ropa, cabello o extremidades en segundos.',
    puntos: ['Nunca retires las guardas de protección de equipos con partes móviles.', 'Evita ropa suelta, cabello sin recoger o accesorios colgantes cerca de maquinaria en movimiento.', 'Apaga y bloquea el equipo antes de realizar cualquier ajuste o limpieza.', 'Mantén siempre una distancia segura de correas, engranajes y rodillos en funcionamiento.'],
    reflexion: 'Los atrapamientos ocurren en un instante: la prevención debe ser constante, no ocasional.',
  },
  {
    titulo: 'Seguridad con equipos de izaje manual (aparejos, poleas)',
    objetivo: 'Aunque no son motorizados, estos equipos también pueden fallar y causar lesiones graves.',
    puntos: ['Verifica la capacidad máxima de carga del aparejo o polea antes de usarlo.', 'Inspecciona ganchos, cadenas y cuerdas en busca de desgaste o daño antes de cada uso.', "Nunca sobrepases la capacidad indicada, aunque 'parezca aguantar'.", 'Mantén a las personas alejadas de la línea de carga durante la maniobra.'],
    reflexion: 'Un equipo manual mal usado puede fallar igual de rápido que uno motorizado.',
  },
  {
    titulo: 'Manejo de emergencias: plan de evacuación',
    objetivo: 'En una emergencia real no hay tiempo para improvisar: el plan debe conocerse de antemano.',
    puntos: ['Conoce las vías de evacuación y salidas de emergencia de tu área de trabajo.', 'Identifica el punto de encuentro asignado antes de que ocurra una emergencia.', 'Participa activamente en los simulacros; son la única forma de estar realmente preparado.', 'Ayuda a otros durante una evacuación si puedes hacerlo sin ponerte en riesgo.'],
    reflexion: 'Conocer el plan de evacuación antes de necesitarlo es lo que marca la diferencia en una emergencia real.',
  },
  {
    titulo: 'Punto de encuentro y roles en emergencia',
    objetivo: 'Cada persona debe saber exactamente qué hacer y a dónde ir en caso de emergencia.',
    puntos: ['Dirígete siempre al punto de encuentro asignado, sin desviarte a buscar pertenencias.', 'Espera el conteo o verificación de asistencia antes de retirarte del punto de encuentro.', 'Si tienes un rol asignado en la brigada de emergencia, conoce tus responsabilidades específicas.', 'Reporta de inmediato si falta alguien de tu equipo en el punto de encuentro.'],
    reflexion: 'En una emergencia, cada segundo cuenta: saber a dónde ir ahorra ese tiempo valioso.',
  },
  {
    titulo: 'Uso de EPP respiratorio',
    objetivo: 'La exposición a polvo, gases o vapores puede causar daño pulmonar irreversible con el tiempo.',
    puntos: ['Usa el tipo de respirador adecuado según el contaminante presente en tu área de trabajo.', 'Verifica el sello facial del respirador antes de cada uso; una mala calce anula su protección.', 'Cambia los filtros según la vida útil indicada por el fabricante o cuando notes dificultad para respirar.', 'Nunca ingreses a zonas con atmósfera peligrosa sin la protección respiratoria adecuada.'],
    reflexion: 'Lo que respiras hoy puede afectar tu salud pulmonar por el resto de tu vida.',
  },
  {
    titulo: 'Trabajo con polvo y sílice',
    objetivo: 'La exposición prolongada a polvo de sílice puede causar silicosis, una enfermedad pulmonar irreversible.',
    puntos: ['Usa sistemas de supresión de polvo (agua, ventilación) siempre que sea posible.', 'Utiliza protección respiratoria certificada para partículas finas en tareas con generación de polvo.', 'Evita tareas en seco cuando existan alternativas húmedas disponibles.', 'Participa en tus controles médicos periódicos si tu trabajo te expone a sílice.'],
    reflexion: 'El daño por sílice es silencioso y acumulativo: la protección diaria es la única defensa real.',
  },
  {
    titulo: 'Almacenamiento seguro de materiales',
    objetivo: 'Un mal apilamiento de materiales puede provocar derrumbes y aplastamientos.',
    puntos: ['Apila los materiales de forma estable, respetando la altura máxima recomendada.', 'Coloca los objetos más pesados en la parte inferior del apilamiento.', 'Verifica que las estanterías no estén sobrecargadas más allá de su capacidad.', 'Mantén los pasillos de circulación libres de materiales almacenados.'],
    reflexion: 'Un material bien almacenado no representa riesgo; uno mal apilado es una amenaza silenciosa.',
  },
  {
    titulo: 'Manejo de cilindros de gas comprimido',
    objetivo: 'Los cilindros de gas comprimido pueden convertirse en proyectiles peligrosos si se dañan o caen.',
    puntos: ['Transporta los cilindros siempre en posición vertical y asegurados con cadenas o soportes.', 'Nunca dejes un cilindro sin su capuchón de protección de válvula cuando no esté en uso.', 'Almacena los cilindros de gases incompatibles separados entre sí.', 'Verifica que no existan fugas antes de usar, mediante los métodos autorizados.'],
    reflexion: 'Un cilindro de gas mal manejado combina riesgo de explosión, incendio y golpe: trátalo siempre con respeto.',
  },
  {
    titulo: 'Seguridad en bodegas y montacargas',
    objetivo: 'Bodegas con tránsito de montacargas combinan riesgos de atropello, caída de materiales y colisión.',
    puntos: ['Respeta siempre las vías peatonales señalizadas dentro de la bodega.', 'Mantén contacto visual con el operador del montacargas antes de cruzar su ruta.', 'Nunca camines bajo cargas elevadas por un montacargas.', 'Los operadores deben usar bocina y luces de advertencia en intersecciones ciegas.'],
    reflexion: 'En una bodega activa, la coordinación constante entre peatones y operadores previene la mayoría de los accidentes.',
  },
  {
    titulo: 'Check list de inicio de jornada',
    objetivo: 'Los primeros minutos del día son la mejor oportunidad para detectar riesgos antes de comenzar a trabajar.',
    puntos: ['Revisa el estado de tu EPP antes de iniciar cualquier tarea.', 'Verifica que tus herramientas y equipos estén en condiciones seguras de uso.', 'Confirma que entiendes claramente la tarea del día y sus riesgos asociados.', 'Comunica de inmediato cualquier condición insegura que detectes al inicio de la jornada.'],
    reflexion: 'Dedicar cinco minutos a revisar antes de empezar puede evitarte horas de consecuencias.',
  },
  {
    titulo: 'Cultura preventiva: todos somos responsables',
    objetivo: 'La seguridad no es responsabilidad de un área o una persona: es una construcción diaria de todo el equipo.',
    puntos: ['Detén cualquier tarea si detectas un riesgo, sin esperar autorización si la situación es urgente.', 'Habla cuando veas una práctica insegura, aunque no sea tu área directa.', 'Reconoce y valora cuando un compañero actúa de forma segura.', 'Entiende que cumplir las normas de seguridad no es una obligación externa, es un cuidado propio y hacia otros.'],
    reflexion: 'Una cultura de seguridad fuerte se construye con miles de pequeñas decisiones correctas, día a día.',
  },
  {
    titulo: 'Cierre de temporada: lecciones aprendidas y mejora continua',
    objetivo: 'Revisar lo vivido en un periodo de trabajo permite mejorar antes de que se repitan los mismos errores.',
    puntos: ['Revisa junto a tu equipo qué incidentes o cuasi accidentes ocurrieron en el periodo reciente.', 'Identifica qué medidas funcionaron bien y cuáles necesitan ajustarse.', 'Reconoce los logros en seguridad del equipo, no solo los problemas.', 'Define compromisos concretos de mejora para el siguiente periodo de trabajo.'],
    reflexion: 'La mejora continua transforma cada experiencia, buena o mala, en una lección útil para el futuro.',
  },
];
